version: "3.8"
# Example compose for SubConverter-Extended.

services:
  subconverter-extended:
    container_name: "SubConverter-Extended"
    image: "aethersailor/subconverter-extended:latest"
    ports:
      - "25500:25500/tcp"
    restart: unless-stopped
    volumes:
      - "./base/pref.toml:/base/pref.toml:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
